name: boxmagic
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.0
  sqflite: ^2.4.2
  path_provider: ^2.1.5
  image_picker: ^1.1.2
  camera: ^0.11.1
  qr_flutter: ^4.1.0
  mobile_scanner: ^6.0.10
  shared_preferences: ^2.5.3
  google_generative_ai: ^0.4.7
  url_launcher: ^6.2.5
  share_plus: ^7.2.2
  pdf: ^3.10.8
  printing: ^5.14.2
  file_picker: ^10.1.2
  universal_html: ^2.2.4
  barcode_widget: ^2.0.4
  image_gallery_saver: ^2.0.3
  permission_handler: ^11.3.0
  pdf_render: ^1.4.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: false
  image_path: "Fotos de icones/magicbox_mascot .png"

flutter:
  uses-material-design: true
  assets:
    - Fotos de icones/magicbox_mascot .png
